export default function CareerSection({ analysis }) {

  if (!analysis) return null;

  const career = analysis.career;

  return (
    <section
      id="career"
      className="bg-[#111827] rounded-2xl shadow-xl border border-slate-700 p-8 transition-all duration-300 hover:border-blue-500"
    >

      <div className="flex justify-between items-center mb-8">

        <div>

          <h2 className="text-2xl font-bold text-white">
            Career Readiness
          </h2>

          <p className="text-slate-400 mt-2">
            Overall evaluation generated by CareerTwin AI
          </p>

        </div>

        <div className="text-center">

          <p className="text-slate-400">
            Overall Score
          </p>

          <p className="text-6xl font-extrabold text-blue-400 mt-2">
            {career.overall_score}%
          </p>

        </div>

      </div>

      {/* Score Cards */}

      <div className="grid md:grid-cols-3 gap-6 mb-10">

        <div className="bg-[#1E293B] border border-slate-700 rounded-xl p-6">

          <h3 className="text-slate-400">
            Skill Score
          </h3>

          <p className="text-4xl font-bold text-cyan-400 mt-3">
            {career.skill_score}%
          </p>

        </div>

        <div className="bg-[#1E293B] border border-slate-700 rounded-xl p-6">

          <h3 className="text-slate-400">
            Project Score
          </h3>

          <p className="text-4xl font-bold text-green-400 mt-3">
            {career.project_score}%
          </p>

        </div>

        <div className="bg-[#1E293B] border border-slate-700 rounded-xl p-6">

          <h3 className="text-slate-400">
            Learning Score
          </h3>

          <p className="text-4xl font-bold text-yellow-400 mt-3">
            {career.learning_score}%
          </p>

        </div>

      </div>

      {/* AI Summary */}

      <div className="bg-blue-900/20 border border-blue-700 rounded-xl p-6 mb-8">

        <h3 className="text-xl font-semibold text-blue-300 mb-4">
          AI Career Summary
        </h3>

        <p className="leading-8 text-slate-300">
          {career.summary}
        </p>

      </div>

      {/* Next Steps */}

      <div className="bg-green-900/20 border border-green-700 rounded-xl p-6">

        <h3 className="text-xl font-semibold text-green-300 mb-5">
          Recommended Next Steps
        </h3>

        <ul className="space-y-4 list-disc ml-6 text-slate-300">

          {career.next_steps.map((step) => (

            <li key={step}>
              {step}
            </li>

          ))}

        </ul>

      </div>

    </section>
  );
}